/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgentPassportInterface extends Interface {
    getFunction(nameOrSignature: "mint" | "nextTokenId"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Minted"): EventFragment;

    encodeFunctionData(functionFragment: 'mint', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextTokenId', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextTokenId', data: BytesLike): Result;
  }

  
    export namespace MintedEvent {
      export type InputTuple = [agent: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [agent: string, tokenId: bigint];
      export interface OutputObject {agent: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentPassport extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentPassport;
    waitForDeployment(): Promise<this>;

    interface: AgentPassportInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    mint: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    nextTokenId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextTokenId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Minted'): TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;

    filters: {
      
      'Minted(address,uint256)': TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
      Minted: TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
    
    };
  }