/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgentMeshEscrowInterface extends Interface {
    getFunction(nameOrSignature: "balances" | "deposit" | "escrows" | "lock" | "releaseFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Locked" | "Released"): EventFragment;

    encodeFunctionData(functionFragment: 'balances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrows', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'lock', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseFunds', values: [BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
  }

  
    export namespace LockedEvent {
      export type InputTuple = [taskId: BytesLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, amount: bigint];
      export interface OutputObject {taskId: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasedEvent {
      export type InputTuple = [taskId: BytesLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, to: string, amount: bigint];
      export interface OutputObject {taskId: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentMeshEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentMeshEscrow;
    waitForDeployment(): Promise<this>;

    interface: AgentMeshEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [taskId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [taskId: BytesLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [taskId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [taskId: BytesLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Locked'): TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
getEvent(key: 'Released'): TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;

    filters: {
      
      'Locked(bytes32,uint256)': TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
      Locked: TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
    

      'Released(bytes32,address,uint256)': TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
      Released: TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
    
    };
  }