FROM node:22-alpine

WORKDIR /usr/src/app

# Cài đặt file config trước
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Chạy server development với cờ watch để tự khởi động lại khi có thay đổi code
EXPOSE 3000
CMD ["npx", "tsx", "watch", "--exclude", "node_modules", "--exclude", "dist", "--exclude", "src", "server/index.ts"]
