/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { AgentPassport, AgentPassportInterface } from "../AgentPassport.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "Minted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "mint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nextTokenId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061019d8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c80631249c58b1461003857806375794a3c14610042575b5f5ffd5b610040610060565b005b61004a6100bd565b60405161005791906100da565b60405180910390f35b5f543373ffffffffffffffffffffffffffffffffffffffff167f30385c845b448a36257a6a1716e6ad2e1bc2cbe333cde1e69fe849ad6511adfe60405160405180910390a35f5f8154809291906100b690610120565b9190505550565b5f5481565b5f819050919050565b6100d4816100c2565b82525050565b5f6020820190506100ed5f8301846100cb565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f61012a826100c2565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff820361015c5761015b6100f3565b5b60018201905091905056fea2646970667358221220709916605d4ad810c234ecb474c7ba91423a85a2efdd250a6a8c4cf8fee64f4164736f6c634300081b0033";

  
      type AgentPassportConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: AgentPassportConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class AgentPassport__factory extends ContractFactory {
    
      constructor(...args: AgentPassportConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<AgentPassport & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): AgentPassport__factory {
      return super.connect(runner) as AgentPassport__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): AgentPassportInterface {
      return new Interface(_abi) as AgentPassportInterface;
    }
    
    override attach(address: string | Addressable): AgentPassport {
      return super.attach(address) as AgentPassport;
    }
  static connect(address: string, runner?: ContractRunner | null): AgentPassport {
      return new Contract(address, _abi, runner) as unknown as AgentPassport;
    }
  }

  
  